// oliapp/src/pages/Auth/SignIn/SignIn.tsx
import { signIn } from "@/api";
import { Alert } from "@/components";
import { type JSXEvent, MessageType } from "@/domain";
import { useForm } from "@/hooks";
import { Lock, Mail } from "@/icons";
import { useAppState } from "@/store";
import { emailValidator, minLenValidator, nonEmptyValidator } from "@/utils/validators";
import { A } from "@solidjs/router";
import { Show, createSignal } from "solid-js";

export default function SignIn() {
	const { handleApiError } = useAppState();
	const [errMsg, setErrMsg] = createSignal("");
	const { form, isValid } = useForm({
		email: {
			validators: [nonEmptyValidator, emailValidator],
		},
		password: {
			validators: [nonEmptyValidator, minLenValidator(6)],
		},
	});

	const closeErrMsg = () => setErrMsg("");

	const handleSubmit = (event: JSXEvent<SubmitEvent, HTMLFormElement>) => {
		event.preventDefault();
		if (!isValid()) {
			return;
		}
		signIn({ email: form.email.value(), password: form.password.value() })
			.then((data) => {
				console.log(data);
			}).catch((err) => {
				handleApiError(err, (msg) => setErrMsg(msg));
			});
	}

	return (
		<div class="flex flex-col items-center">
			<h1 class="text-3xl scroll-m-20 font-extrabold tracking-tight mb-2">Bienvenido a OLIAI</h1>

			<Show when={errMsg().length > 0}>
				<Alert message={errMsg()} variant={MessageType.WARNING} onClose={closeErrMsg} />
			</Show>

			<form class="self-stretch flex flex-col gap-2 mt-2" onSubmit={handleSubmit}>
				<label class="form-control">
					<div class="label">
						<span class="label-text">Correo</span>
					</div>
					<span class="input input-bordered flex items-center gap-2">
						<Mail class="text-lg" />
						<input
							value={form.email.value()}
							onInput={form.email.onInput}
							type="email"
							placeholder="ejemplo@mail.com"
							autocapitalize="off"
							autocomplete="email"
							class="grow"
							required
						/>
					</span>
					<div class="label">
						<span class="label-text-alt text-error">{form.email.error()}</span>
					</div>
				</label>
				<label class="form-control">
					<div class="label">
						<span class="label-text">Contraseña</span>
					</div>
					<span class="input input-bordered flex items-center gap-2">
						<Lock class="text-lg" />
						<input
							value={form.password.value()}
							onInput={form.password.onInput}
							type="password"
							placeholder="* * * * * * *"
							required
						/>
					</span>
					<div class="label">
						<span class="label-text-alt text-error">{form.password.error()}</span>
					</div>
				</label>
				<button type="submit" class="btn btn-primary mt-2">
					Ingresar
				</button>
				<p class="self-end text-base mt-2">
					¿Aún no tienes una cuenta?
					<A href="/auth/signup" class="link link-primary font-semibold"> Registrarme</A>
				</p>
			</form>
			<div class="h-2 md:h-32" />
		</div >
	);
}

// oliapp/src/routes/auth/signin/SignIn.vue
<script setup lang="ts">
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { RouterLink } from "vue-router";
</script>
<template>
	<div class="flex flex-col items-center">
		<h1 class="text-3xl scroll-m-20 font-extrabold tracking-tight">Ingresar</h1>

		<form class="self-stretch flex flex-col gap-2 mt-4">
			<div class="">
				<Label for="email">Correo</Label>
				<Input id="email" type="email" placeholder="ejemplo@mail.com" autocapitalize="off" autocomplete="email" />
			</div>
			<div class="">
				<Label for="password">Contraseña</Label>
				<Input id="password" type="password" placeholder="" />
			</div>
			<Button class="font-bold text-base mt-2">Ingresar</Button>
			<p class="self-end text-base mt-2">
				¿Aún no tienes una cuenta?
				<RouterLink :to="{ name: 'signup' }" class="underline underline-offset-4">Registrarme</RouterLink>
			</p>
		</form>
		<div class="h-2 md:h-32"></div>
	</div>
</template>
